version: '1.0.1'
services:
    dbs-java:
        build: .
        ports:
            - 8000:8000
        environment:
            - DATABASE_PORT=5432
            - DATABASE_HOST=10.10.1.103
            - DATABASE_NAME=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=111111